version: '3.8'
services:
  db:
    build: ./small-basket-database
    container_name: small-basket-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: vegshop
    volumes:
      - ./small-basket-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - small-basket-db-data:/var/lib/mysql

  backend:
    build: ./small-basket-backend
    container_name: small-basket-backend
    ports:
      - "5000:5000"
    env_file:
      - ./small-basket-backend/.env
    depends_on:
      - db

  frontend:
    build: ./small-basket-frontend
    container_name: small-basket-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  small-basket-db-data:
