version: '3.8'
services:
  db:
    image: mysql:8
    container_name: small-basket-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./small-basket-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - small-basket-db-data:/var/lib/mysql

  backend:
    build: ./small-basket-backend
    container_name: small-basket-backend
    ports:
      - "5000:5000"
    env_file:
      - ./small-basket-backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./small-basket-frontend
    container_name: small-basket-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./small-basket-frontend/public/config.js:/app/build/config.js:ro
    depends_on:
      - backend

volumes:
  small-basket-db-data:
